# Generated by Django 4.2.2 on 2023-06-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/thumbnails/'),
        ),
        migrations.AddField(
            model_name='tech',
            name='logo',
            field=models.ImageField(default='', upload_to='images/logos/'),
        ),
    ]
